
name: Nightly

on:
  schedule:
    - cron: "59 23 * * *"

jobs:
  build:
    defaults:
      run: { shell: bash }
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Build Project
        uses: ./.github/actions/gradle
      - name: Check Build
        run: ls -AlF core/build

  sample_keystores:
    defaults:
      run: { shell: bash }
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Sample Keystores (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Create Sample Keystores
        uses: ./.github/actions/gradle
        with:
          tasks: createCa createIdentities

  build_site:
    name: Build Site
    runs-on: ubuntu-latest
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Install Java
        uses: actions/setup-java@v3
        with: { java-version: 17, distribution: temurin, cache: gradle }
      - name: Install ImageMagick
        uses: ./.github/actions/image_magick
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-mkdocs-
          path: |
            ~/.local/bin
            ~/.local/lib/python*/site-packages

      # PROCESS
      - name: Build Site
        run: |
          ./gradlew --info build
          ./gradlew --info -x build buildSite
          ls -AlF site/build/site

  test_publishing:
    defaults:
      run: { shell: bash }
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Test Publishing (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Test Publishing
        uses: ./.github/actions/gradle
        with:
          tasks: --no-daemon publishToMavenLocal -x test
